### ISSUE TITLE
Argument must be a string Error

### ISSUE THREAD

**Issue by aug-riedinger** [adunkman/connect-assets#289]
Using the `node-sass` package and `connect-assets`

```
    // extract from package.json
    "jade": "~1.9.0",
    "node-sass": "~2.0.0-beta",
    "connect-assets": "~4.3.3"
```

I have `index.html.jade` which works fine and has:

```
    != css('application')
```

Works pretty well in css:

```
/* 
 *= require normalize.css/normalize
 *= require bootstrap/dist/css/bootstrap
 *= require_tree .
 * require test/test-scss
*/
```
But if I add a scss file (here `test/test-scss.css.scss`):
```
/* 
 *= require normalize.css/normalize
 *= require bootstrap/dist/css/bootstrap
 *= require_tree .
 *= require test/test-scss
*/
```
I get the following error:

```
TypeError: [...]/index.html.jade:4
   2| html(lang="en")
   3|   head
 > 4|     != css('application')
   5|   body
   6|     h1 Hello dude
   7|     p Cool huh?

Argument must be a string
   at new ProcessedAsset (/home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/assets/processed.js:149:24)
   at /home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:541:12
   at circular_call_protection (/home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:514:12)
   at Index.Base.buildAsset (/home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:540:10)
   at /home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/index.js:142:26
   at Index.module.exports.cacheAsset (/home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/helpers/caching.js:52:12)
   at Index.buildAsset (/home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/index.js:141:33)
   at Index.Base.findAsset (/home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/base.js:350:15)
   at Index.findAsset (/home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/index.js:115:22)
   at /home/augustin/Workspace/meeting point/node_modules/connect-assets/node_modules/mincer/lib/mincer/assets/processed.js:53:30
```

I have tried many things around like `*= require test/test-scss.css`, ` *= require test/test-scss.css.scss`, ` *= require 'test/test-scss'`.

I hardly know where to look at. Being searching for the error in the Mincer source code, but without success.

Help would be much appreciated!

Thanks

**Comment by gabooh** [comment]
I'm getting this issue too with node-sass 2.0.0-beta but not with version 1.2.3.

**Comment by adunkman** [comment]
This is most likely an issue within mincer — likely a change in the API of the node-sass compiler or response from the node-sass compiler functions.

**Comment by adunkman** [comment]
If you want to go spelunking into mincer, I’d start with the [SassEngine](https://github.com/nodeca/mincer/blob/0d3bac5489379c14ce24ad002a3fa09230eb775e/lib/mincer/engines/sass_engine.js) and see if any of that needs to change between the latest stable release of node-sass and their beta release.

**Comment by gabooh** [comment]
I'll see If I can find time for this, but it doesn't like so for now. Thanks for the help!

**Comment by chinmayrane** [comment]
Any Solution did anyone find? Anything I need to upgrade or degrade to ?

**Comment by gabooh** [comment]
Fixed with https://github.com/nodeca/mincer/pull/186

**Comment by adunkman** [comment]
@gabooh :heart: :) 

I’ll leave this open until we publish a version with the new mincer version, since the error will still be happening here until then.

**Comment by Barnabas** [comment]
nodeca/mincer#186 has been closed, mincer has been updated to 1.2.3. Thanks!

**Comment by aug-riedinger** [comment]
I have `"connect-assets": "^4.7.0",` and its `package.json` there is:

```
  "dependencies": {
    "argparse": "0.1.16",
    "csswring": "3.0.0",
    "mincer": "1.2.4",
    "uglify-js": "2.4.16"
  },
```

But I still get the error. Anything else to do to make it work?

Thanks

**Comment by nmalacarne** [comment]
I ran into this issue when using Node v0.10.38. Switching to Node v0.12.3 fixed the problem.

**Comment by adunkman** [comment]
We’ve since published a new version with new mincer, so I’m considering this resolved. Yell if you disagree! :)

**Comment by aug-riedinger** [comment]
Thanks, I'll update this!
